# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tl_label_map.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tl_label_map.proto',
  package='tl_protos',
  serialized_pb=_b('\n\x12tl_label_map.proto\x12\ttl_protos\"(\n\x0cTrafficLight\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0c\n\x04name\x18\x02 \x02(\t\"8\n\x0fTrafficLightMap\x12%\n\x04item\x18\x01 \x03(\x0b\x32\x17.tl_protos.TrafficLight')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TRAFFICLIGHT = _descriptor.Descriptor(
  name='TrafficLight',
  full_name='tl_protos.TrafficLight',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='tl_protos.TrafficLight.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='tl_protos.TrafficLight.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=73,
)


_TRAFFICLIGHTMAP = _descriptor.Descriptor(
  name='TrafficLightMap',
  full_name='tl_protos.TrafficLightMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item', full_name='tl_protos.TrafficLightMap.item', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=131,
)

_TRAFFICLIGHTMAP.fields_by_name['item'].message_type = _TRAFFICLIGHT
DESCRIPTOR.message_types_by_name['TrafficLight'] = _TRAFFICLIGHT
DESCRIPTOR.message_types_by_name['TrafficLightMap'] = _TRAFFICLIGHTMAP

TrafficLight = _reflection.GeneratedProtocolMessageType('TrafficLight', (_message.Message,), dict(
  DESCRIPTOR = _TRAFFICLIGHT,
  __module__ = 'tl_label_map_pb2'
  # @@protoc_insertion_point(class_scope:tl_protos.TrafficLight)
  ))
_sym_db.RegisterMessage(TrafficLight)

TrafficLightMap = _reflection.GeneratedProtocolMessageType('TrafficLightMap', (_message.Message,), dict(
  DESCRIPTOR = _TRAFFICLIGHTMAP,
  __module__ = 'tl_label_map_pb2'
  # @@protoc_insertion_point(class_scope:tl_protos.TrafficLightMap)
  ))
_sym_db.RegisterMessage(TrafficLightMap)


# @@protoc_insertion_point(module_scope)
